parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: '3306'
    database_name: npprofile
    database_user: npprofile
    database_password: rahasiaya!
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 6bfc54f6ab3d9641751d43ebfa0910348
    database_path: null