parameters:
#    negeri_pelangi_user.example.class: NegeriPelangi\UserBundle\Example

services:
#    negeri_pelangi_user.example:
#        class: %negeri_pelangi_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
